accepted = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "BSL-1.0",
  "MPL-2.0",
  "CC0-1.0",
  "ISC",
  "Zlib",
  "OpenSSL",
  "0BSD",
  "Unicode-DFS-2016",
]

no-clearly-defined = true

workarounds = [
  "ring",
]
