[package]
edition = "2021"
name = "annis-web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = {version = "0.6.1", features = ["headers"]}
axum-sessions = "0.4.1"
include_dir = "0.7"
mime_guess = "2"
rand = "0.8"
reqwest = {version = "0.11", features = ["json"]}
serde = "1"
thiserror = "1"
tokio = {version = "1.17.0", features = ["rt-multi-thread", "macros"]}
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.3"

[dev-dependencies]
fantoccini = "0.19"
hyper = {version = "0.14", features = ["full"]}
mockito = "0.31"
scraper = "0.13"
tower = {version = "0.4", features = ["util"]}
tracing-test = "0.2"
