[package]
edition = "2021"
name = "annis-web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = "0.6.1"
include_dir = "0.7"
mime_guess = "2"
thiserror = "1"
tokio = {version = "1.17.0", features = ["rt-multi-thread", "macros"]}

[dev-dependencies]
hyper = {version = "0.14", features = ["full"]}
scraper = "0.13"
tower = {version = "0.4", features = ["util"]}
