name: Execute automated tests

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
